### ISSUE TITLE
Typo in resource_database.go

### ISSUE THREAD

**Issue by davemasino** [ShopRunner/terraform-provider-snowflake#6]
dbName := d.Get(whNameAttr).(string)   should be....
dbName := d.Get(dbNameAttr).(string)

The code works as is but ideally should be fixed

**Comment by justinrmiller** [comment]
I've addressed this in https://github.com/ShopRunner/terraform-provider-snowflake/pull/11, please take a look and see if I caught all the instances of this.

**Comment by davemasino** [comment]
@justinrmiller thanks for fixing! Looks good.
