### ISSUE TITLE
Looking for contributors?

### ISSUE THREAD

**Issue by darrenhaken** [ShopRunner/terraform-provider-snowflake#7]
Hi there,

We're starting to use Snowflake and are big TF users, any appetite for contributions?

**Comment by darrenhaken** [comment]
Awesome! Does the provider support users already?

**Comment by whittid4** [comment]
Hi @sadhasivam. I am a colleague of @darrenhaken. 

We have been working on getting the users resource to work. We now have this working and would you accept a pull request for this?

**Comment by sadhasivam** [comment]
@whittid4  happy to accept PR. please contribute.

**Comment by PaulW** [comment]
Pull request has been submitted to enable basic management of users via the provider #8 
Also included are some updates to the `README.md` to help clarify these additions.

**Comment by justinrmiller** [comment]
Can this PR be closed out? I've also submitted a pull request (#11).

**Comment by darrenhaken** [comment]
Yep
